services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www/www

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www

  mysql:
    image: mysql:8.2
    restart: unless-stopped
    ports:
      - "3316:3306"                # доступ извне
    env_file:
      - env/mysql.env              # переменные окружения
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: